Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ./task-definition.json
        LoadBalancerInfo: 
          ContainerName: "nginx" 
          ContainerPort: 80